name: test

on:
  push:
    branches:
      - 'main'
      - 'feature/**'
  pull_request:
    branches:
      - 'main'
  schedule:
    - cron: '00 00 * * 3'
  workflow_dispatch:
    inputs:
      tfBackend:
        type: choice
        description: Specify the backend to use
        default: 'local'
        options:
          - local
          - azurerm

permissions:
  id-token: write
  contents: read

jobs:
  test:
    strategy:
      matrix:
        platform:
          - 'ubuntu-latest'
        node-version:
          - '22.12.0'
        terraform-version:
          - '1.11.3'
    runs-on: ${{ matrix.platform }}
    environment: dev
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_USE_OIDC: ${{secrets.ARM_USE_OIDC}}
      TF_BACKEND: ${{ github.event.inputs.tfBackend || 'local' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # to retrieve git tags
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ matrix.terraform-version }}
      - name: Install Trivy
        uses: aquasecurity/setup-trivy@v0.2.2
        with:
          version: v0.61.0
          cache: true
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.56.0
      - uses: pnpm/action-setup@v4
        with:
          version: 9.15.2
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Run CI tests with backend=${{ github.event.inputs.tfBackend || 'local' }}
        shell: bash
        run: |
          make ci-test
