name: test

on:
  push:
    branches:
      - "main"
      - "feature/**"
  pull_request:
    branches:
      - "main"

jobs:
  test:
    strategy:
      matrix:
        platform:
          - "ubuntu-latest"
        node-version:
          - "22.12.0"
        terraform-version:
          - "1.11.3"
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # to retrieve git tags
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ matrix.terraform-version }}
      - uses: pnpm/action-setup@v4
        with:
          version: 9.15.2
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Run CI tests
        shell: bash
        run: |
          make ci-test
